version: "3"
services:
  app:
    image: stefanijac182019/vetclinic:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vetclinic-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/app-db
    ports:
      - 8081:8081
    depends_on:
      - database

  database:
    image: postgres
    container_name: vetclinic-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stefanijac
      - POSTGRES_DB=app-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: